// <auto-generated />
using System;
using Four;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Four.Migrations
{
    [DbContext(typeof(DbContextFour))]
    [Migration("20210926025735_AddValueCustomer")]
    partial class AddValueCustomer
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Four.Entity.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CreateBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("UpdateBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Ngã 4 Khuất Duy Tiến",
                            CreateDate = new DateTime(2021, 9, 26, 9, 57, 34, 563, DateTimeKind.Local).AddTicks(9807),
                            DateOfBirth = new DateTime(2021, 9, 26, 9, 57, 34, 564, DateTimeKind.Local).AddTicks(9713),
                            Gender = 1,
                            Name = "Thúy Thị Kiều",
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            Address = "Ngã 3 Khuất Duy Tiến",
                            CreateDate = new DateTime(2021, 9, 26, 9, 57, 34, 565, DateTimeKind.Local).AddTicks(259),
                            DateOfBirth = new DateTime(2021, 9, 26, 9, 57, 34, 565, DateTimeKind.Local).AddTicks(293),
                            Gender = 1,
                            Name = "Thúy Thị Vân",
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            Address = "Ngã 4 Trần Duy Hưng",
                            CreateDate = new DateTime(2021, 9, 26, 9, 57, 34, 565, DateTimeKind.Local).AddTicks(314),
                            DateOfBirth = new DateTime(2021, 9, 26, 9, 57, 34, 565, DateTimeKind.Local).AddTicks(316),
                            Gender = 0,
                            Name = "Chí Phèo",
                            Status = 0
                        },
                        new
                        {
                            Id = 4,
                            Address = "Ngã 4 Thanh Xuân",
                            CreateDate = new DateTime(2021, 9, 26, 9, 57, 34, 565, DateTimeKind.Local).AddTicks(317),
                            DateOfBirth = new DateTime(2021, 9, 26, 9, 57, 34, 565, DateTimeKind.Local).AddTicks(318),
                            Gender = 0,
                            Name = "Lão Hạc",
                            Status = 0
                        },
                        new
                        {
                            Id = 5,
                            Address = "Ngã 3 Dịch Vọng",
                            CreateDate = new DateTime(2021, 9, 26, 9, 57, 34, 565, DateTimeKind.Local).AddTicks(507),
                            DateOfBirth = new DateTime(2021, 9, 26, 9, 57, 34, 565, DateTimeKind.Local).AddTicks(509),
                            Gender = 0,
                            Name = "Cậu Vàng",
                            Status = 0
                        });
                });

            modelBuilder.Entity("Four.Entity.DetailsInvoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<Guid?>("CreateBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("InvoiceID")
                        .HasColumnType("int");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("UpdateBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceID");

                    b.HasIndex("ProductID");

                    b.ToTable("DetailsInvoices");
                });

            modelBuilder.Entity("Four.Entity.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid?>("CreateBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("InvoiceDay")
                        .HasColumnType("datetime2");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("UpdateBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CustomerID");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("Four.Entity.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid?>("CreateBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdateBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("Four.Entity.DetailsInvoice", b =>
                {
                    b.HasOne("Four.Entity.Invoice", "Invoice")
                        .WithMany("DetailsInvoices")
                        .HasForeignKey("InvoiceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Four.Entity.Product", "Product")
                        .WithMany("DetailsInvoices")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Four.Entity.Invoice", b =>
                {
                    b.HasOne("Four.Entity.Customer", "Customer")
                        .WithMany("Invoices")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Four.Entity.Customer", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("Four.Entity.Invoice", b =>
                {
                    b.Navigation("DetailsInvoices");
                });

            modelBuilder.Entity("Four.Entity.Product", b =>
                {
                    b.Navigation("DetailsInvoices");
                });
#pragma warning restore 612, 618
        }
    }
}
